import {
	ActivityIcon,
	ArrowClockwise,
	ArrowCounterClockwise,
	ArrowLeft,
	ArrowRight,
	ArrowSquareOut,
	ArrowUpRight,
	Bell,
	BookOpen,
	Brain,
	Bug,
	Calendar,
	CaretDown,
	CaretLeft,
	CaretRight,
	CaretUp,
	CaretUpDown,
	ChartBar,
	ChartLine,
	ChartPie,
	ChatCircle,
	ChatCircleText,
	Check,
	CheckCircle,
	Circle,
	ClipboardText,
	Clock,
	Code,
	Cpu,
	Desktop,
	DeviceMobile,
	DotsThree,
	DotsThreeVertical,
	Download,
	Envelope,
	EnvelopeSimple,
	Eye,
	EyeSlash,
	FileCode,
	FileLock,
	FileMagnifyingGlass,
	FileText,
	Fingerprint,
	Fish,
	Flag,
	Flame,
	FloppyDisk,
	Funnel,
	GameController,
	Gauge,
	Gear,
	Globe,
	GraduationCap,
	Hash,
	House,
	Info,
	Key,
	Laptop,
	Lightning,
	List,
	ListChecks,
	Lock,
	LockKey,
	LockSimpleOpen,
	MagnifyingGlass,
	Medal,
	Moon,
	Network,
	NotePencil,
	PaperPlaneTilt,
	Pencil,
	Play,
	PlayCircle,
	Plus,
	PuzzlePiece,
	Question,
	Scan,
	SignIn,
	SignOut,
	Shield,
	ShieldCheck,
	ShieldSlash,
	ShieldWarning,
	ShoppingBag,
	Sparkle,
	Spinner,
	SquaresFour,
	Stack,
	Star,
	Sun,
	Target,
	TerminalWindow,
	Timer,
	Trash,
	TrendUp,
	Trophy,
	Upload,
	User,
	UserPlus,
	Users,
	Warning,
	WarningCircle,
	WifiHigh,
	WifiSlash,
	X,
	XCircle,
} from '@phosphor-icons/react/ssr'
import type { Icon } from '@phosphor-icons/react/lib'

// Compatibility names keep persisted icon values and existing component APIs
// stable while every rendered glyph comes from Phosphor.
export type AppIcon = Icon

export {
	ActivityIcon as Activity,
	WarningCircle as AlertCircle,
	Warning as AlertTriangle,
	ArrowLeft,
	ArrowRight,
	ArrowUpRight,
	Medal as Award,
	ChartBar as BarChart3,
	Bell,
	BookOpen,
	Brain,
	Calendar,
	Calendar as CalendarDays,
	ChartLine,
	Check,
	CheckCircle,
	CheckCircle as CheckCircle2,
	Check as CheckIcon,
	CaretDown as ChevronDown,
	CaretDown as ChevronDownIcon,
	CaretLeft as ChevronLeft,
	CaretRight as ChevronRight,
	CaretRight as ChevronRightIcon,
	CaretUp as ChevronUpIcon,
	CaretUpDown as ChevronsUpDown,
	Question as CircleHelp,
	Circle as CircleIcon,
	ClipboardText as ClipboardList,
	Clock,
	Code as Code2,
	Cpu,
	Download,
	Pencil as Edit,
	NotePencil as Edit2,
	ArrowSquareOut as ExternalLink,
	Eye,
	EyeSlash as EyeOff,
	FileMagnifyingGlass as FileQuestion,
	FileText,
	Funnel as Filter,
	Fish as FishingHook,
	Flag,
	GameController as Gamepad2,
	Gauge,
	Globe,
	GraduationCap,
	Hash,
	House as Home,
	Question as HelpCircle,
	Info,
	Key,
	Laptop,
	Stack as Layers,
	SquaresFour as LayoutDashboard,
	ListChecks,
	Spinner as Loader2,
	Lock,
	LockKey as LockKeyhole,
	LockSimpleOpen as LockOpen,
	SignIn as LogIn,
	SignOut as LogOut,
	Envelope as Mail,
	EnvelopeSimple as MailCheck,
	List as Menu,
	ChatCircle as MessageCircle,
	ChatCircleText as MessageSquarePlus,
	ChatCircleText as MessageSquareText,
	Desktop as Monitor,
	Moon,
	DotsThree as MoreHorizontal,
	DotsThreeVertical as MoreVertical,
	Network,
	Play,
	PlayCircle,
	Plus,
	PuzzlePiece as Puzzle,
	ArrowClockwise as RefreshCw,
	ArrowCounterClockwise as RotateCcw,
	FloppyDisk as Save,
	MagnifyingGlass as ScanSearch,
	MagnifyingGlass as Search,
	MagnifyingGlass as SearchIcon,
	PaperPlaneTilt as Send,
	Gear as Settings,
	Shield,
	ShieldWarning as ShieldAlert,
	ShieldCheck,
	Question as ShieldQuestion,
	ShoppingBag,
	DeviceMobile as Smartphone,
	Sparkle as Sparkles,
	Star,
	Sun,
	Target,
	Timer,
	Trash as Trash2,
	TrendUp as TrendingUp,
	Trophy,
	User,
	UserPlus,
	Users,
	WifiSlash as WifiOff,
	X,
	XCircle,
	X as XIcon,
	Lightning as Zap,
}

export const icons: Record<string, AppIcon> = {
	Activity: ActivityIcon,
	AlertCircle: WarningCircle,
	AlertTriangle: Warning,
	ArrowLeft,
	ArrowRight,
	ArrowUpRight,
	Award: Medal,
	BarChart3: ChartBar,
	Bell,
	BookOpen,
	Brain,
	Calendar,
	CalendarDays: Calendar,
	ChartLine,
	Check,
	CheckCircle,
	CheckCircle2: CheckCircle,
	ChevronDown: CaretDown,
	ChevronLeft: CaretLeft,
	ChevronRight: CaretRight,
	ChevronUp: CaretUp,
	ChevronsUpDown: CaretUpDown,
	CircleHelp: Question,
	ClipboardList: ClipboardText,
	Clock,
	Code2: Code,
	Cpu,
	Download,
	Edit: Pencil,
	Edit2: NotePencil,
	ExternalLink: ArrowSquareOut,
	Eye,
	EyeOff: EyeSlash,
	FileQuestion: FileMagnifyingGlass,
	FileText,
	Filter: Funnel,
	FishingHook: Fish,
	Flag,
	Gamepad2: GameController,
	Gauge,
	Globe,
	GraduationCap,
	Hash,
	HelpCircle: Question,
	Home: House,
	Info,
	Key,
	Laptop,
	Layers: Stack,
	LayoutDashboard: SquaresFour,
	ListChecks,
	Loader2: Spinner,
	Lock,
	LockKeyhole: LockKey,
	LockOpen: LockSimpleOpen,
	LogIn: SignIn,
	LogOut: SignOut,
	Mail: Envelope,
	MailCheck: EnvelopeSimple,
	Menu: List,
	MessageCircle: ChatCircle,
	MessageSquarePlus: ChatCircleText,
	MessageSquareText: ChatCircleText,
	Monitor: Desktop,
	Moon,
	MoreHorizontal: DotsThree,
	MoreVertical: DotsThreeVertical,
	Network,
	Play,
	PlayCircle,
	Plus,
	Puzzle: PuzzlePiece,
	RefreshCw: ArrowClockwise,
	RotateCcw: ArrowCounterClockwise,
	Save: FloppyDisk,
	ScanSearch: MagnifyingGlass,
	Search: MagnifyingGlass,
	Send: PaperPlaneTilt,
	Settings: Gear,
	Shield,
	ShieldAlert: ShieldWarning,
	ShieldCheck,
	ShieldQuestion: Question,
	ShoppingBag,
	Smartphone: DeviceMobile,
	Sparkles: Sparkle,
	Star,
	Sun,
	Target,
	Timer,
	Trash2: Trash,
	TrendingUp: TrendUp,
	Trophy,
	User,
	UserPlus,
	Users,
	WifiOff: WifiSlash,
	X,
	XCircle,
	Zap: Lightning,
	ShieldOff: ShieldSlash,
	Unlock: LockSimpleOpen,
	KeyRound: Key,
	Fingerprint,
	Library: BookOpen,
	School: GraduationCap,
	Terminal: TerminalWindow,
	Binary: Code,
	Database: Stack,
	Server: Network,
	HardDrive: Stack,
	Wifi: WifiHigh,
	Bug,
	Venom: Bug,
	Skull: Warning,
	Flame,
	Scan,
	SearchCode: Code,
	Radar: Scan,
	FileCode,
	FileLock,
	FileSearch: FileMagnifyingGlass,
	FileWarning: Warning,
	LineChart: ChartLine,
	PieChart: ChartPie,
	History: ArrowCounterClockwise,
	Edit3: Pencil,
	Upload,
	InfoCircle: Info,
	Share2: ArrowSquareOut,
	Bookmark: Star,
}
